### ISSUE TITLE
required custom OCR model

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Air-Writing-To-Speech#1]
- We need to develop an OCR model that converts the handwritten image to text.
- Design workflow and update.

**Comment by prashanthm07** [comment]
okay! I'll update once done.

**Comment by prashanthm07** [comment]
@RitheeshBaradwaj  I got the dataset. It looks fine.  I wonder whether we want to classify both lowercase and uppercase characters as one class? Also, can you just create another branch for OCR or should I use master itself directly?
![train_41_00015](https://user-images.githubusercontent.com/37323998/84594093-82f53e00-ae6d-11ea-8fc0-f92858cd4334.png)
![train_61_00027](https://user-images.githubusercontent.com/37323998/84594102-8ee10000-ae6d-11ea-89d7-909111694e52.png)

**Comment by RitheeshBaradwaj** [comment]
That looks good. As per our current requirement classify both of them into single class. You need to create a branch with name 'feature_ocr' , keep all your files in OCR model directory and commit your files. Then create a PR!

**Comment by prashanthm07** [comment]
I'm not able to create the branch.

**Comment by prashanthm07** [comment]
@RitheeshBaradwaj  Well, I've gone through various blogs and posts, all that I got is, our task becomes quite difficult if we train the characters separately and then trying to predict each of them either by using segmentation or using OpenCV(It took somewhere around 12.5sec when used segmentation(In a blog post).  So, I feel that if we can train it over the words and its corresponding labels, it might work for us.  Let me know what do you think?

**Comment by RitheeshBaradwaj** [comment]
Yes @mangipudiprashanth7 please go ahead, but make sure you cover some common greeting words and any words related to current situation. Can we do that?

**Comment by prashanthm07** [comment]
Yes. I'll update more info by tomorrow EOD.

**Comment by prashanthm07** [comment]
@RitheeshBaradwaj  Can you send some 5-10 samples of the output of  air_2img?

**Comment by RitheeshBaradwaj** [comment]
Yeah sure! I am attaching some samples. @santhoshbandaru you please generate some other samples and attach here!<br>
![result1506](https://user-images.githubusercontent.com/48406715/84979967-5fbcde00-b14e-11ea-968d-2c5e1dcea244.jpg)
![result1247](https://user-images.githubusercontent.com/48406715/84979998-824ef700-b14e-11ea-8553-d15e6f8fa1f5.jpg)
![result1170](https://user-images.githubusercontent.com/48406715/84980005-84b15100-b14e-11ea-9329-2f0a8eae1d9e.jpg)
![result2024](https://user-images.githubusercontent.com/48406715/84980006-8713ab00-b14e-11ea-8033-63f1c3a4ebbb.jpg)
![result282](https://user-images.githubusercontent.com/48406715/84980010-8b3fc880-b14e-11ea-992c-5965e41feb17.jpg)

**Comment by prashanthm07** [comment]
@RitheeshBaradwaj 
- Updated the branch with the model file and other necessary files. 
- Need to finalize the preprocessing while predicting the text from the image, that is taken from the air_to_image function. 
I've tried a couple of methods which include adjusting gamma values, thickness, and the contrast of the image pixels.
- Once, the preprocessing part is made perfect, then we are good to go. I mean we can still, integrate it with the air_to_img part. It's just that we might not be able to get great predictions from the model. The reason is because of the way the model is trained.
![sample1](https://github.com/developers-cosmos/Air-Writing-To-Speech/blob/feature_ocr/readme_data/test.png)
![sample2](https://github.com/developers-cosmos/Air-Writing-To-Speech/blob/feature_ocr/readme_data/test2.png)

- I guess we can make more progress if we can build our own custom data.  I'm looking for other ways as well. 
- README is still undone. 
- FYI, I've not written the code from the scratch, I've referred other blogs and GitHub repositories, I'll put the links in the references section while updating readme.
